### Register User Test 
POST http://localhost:3010/register
Content-Type: application/json

{
  "username": "Nandi",
  "password": "Password"
}
### Login User Test 
POST http://localhost:3010/login
Content-Type: application/json

{
  "username": "Nandi",
  "password": "Password"
}

### Create Task Test
POST http://localhost:3010/tasks/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJOYW5kaSIsInBhc3N3b3JkIjoiJDJiJDEwJENobFRPc2pOMUR5Z1lNai9FZW5QcU9pWmtodHF0M05INTZocy80VzNEZlNEVXVHMkxieFcuIiwiaWF0IjoxNzMzMjM1OTYyLCJleHAiOjE3MzMyMzk1NjJ9.L741niOvUi8Bf0FZ25sEmWrsxrYE58izCnGVPWEuuIM

{
  "title": "complete assessment",
  "description": "Change Typescript project to JS", 
  "due_date": "2024-12-01",
  "status": false
}

### View user Tasks 
GET http://localhost:3010/tasks/user
Content-Type: application/json
{
  "id": 3
}

### Update Task test 
POST http://localhost:3010/tasks/update
Content-Type: application/json

{
  "title": "complete assessment"
}

### delete Task Test 
POST http://localhost:3010/tasks/delete
Content-Type: application/json

{
  "title": "complete assessment"
}

